---
# tasks file for ansible-role-tftpd
- name: include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "default.yml"

- name: install software
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ packages }}"

- name: create tfptroot
  file:
    path: "{{ tftproot }}"
    state: directory

- name: enable tftpd in stat_xinetd
  template:
    src: templates/tftp.j2
    dest: /etc/xinetd.d/tftp
