---
# tasks file for tftpd
- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ tftpd_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
        | default(tftpd_packages[ansible_distribution]
        | default(tftpd_packages['default'] )) }}"

- name: create tfptroot
  file:
    path: "{{ tftpd_tftproot }}"
    state: directory

- name: enable tftpd in xinetd
  template:
    src: tftp.j2
    dest: /etc/xinetd.d/tftp
  notify:
    restart xinetd
  when:
    - ansible_virtualization_type != "docker"
