---
# tasks file for tftpd
- name: include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "tftpd.{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "tftpd.{{ ansible_distribution }}.yml"
    - "tftpd.default.yml"

- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ tftpd_packages }}"

- name: create tfptroot
  file:
    path: "{{ tftpd_tftproot }}"
    state: directory

- name: enable tftpd in xinetd
  template:
    src: templates/tftp.j2
    dest: /etc/xinetd.d/tftp
  notify:
    restart xinetd
  when:
    - ansible_virtualization_type != "docker"
