---
# tasks file for tftpd
- name: install tftpd
  package:
    name: "{{ tftpd_packages[ansible_distribution]
          | default(tftpd_packages['default']) }}"
    state: "{{ tftpd_package_state }}"

- name: create tfptroot
  file:
    path: "{{ tftpd_tftproot }}"
    state: directory

- name: enable tftpd in xinetd
  template:
    src: tftp.j2
    dest: /etc/xinetd.d/tftp
  notify:
    restart xinetd
